default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: username
      password: password
      host:     <%= ENV['IP'] %>
      timeout: 5000

development:
  <<: *default
  database: instapost_development

test:
  <<: *default
  database: instapost_test

production:
  <<: *default
  database: instapost_production